server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Panzhenyu1234
    url: jdbc:mysql://pzy123.top:3306/bysj?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # 地址
    host: 121.199.49.79
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码(如没有密码请注释掉)
    password: 798313
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
mqtt:
  host: tcp://lora.heltec.org:1883 #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
  clientId: pzy
  userName: 798313762   #MQTT-用户名
  passWord: NNSXS.L7FZESBDL5YFDAZHQYGEW4HW64QSLKS3GDNQATA.2JH2BWWGZG6LQCTT5MXB4Y75G4K33G7ECJDSFTCKPDPE7IG6L5ZQ #MQTT-密码
  default-topic: test #MQTT-默认的消息推送主题，实际可在调用接口时指定
  timeOut: 1000 #连接超时
  keepaLive: 30   #设置会话心跳时间
  clearSession: true  #清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)
  topic1: v3/798313762/devices/eui-81fa12f400004061/up
  topic2: v3/798313762/devices/eui-81fa12f40000c858/up
